language: scala
jdk:
  - oraclejdk12
sudo: false
scala:
   - 2.11.8
   - 2.12.0
   - 2.13.0
script:
  - sbt clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)